version: '3'

services:

  vue:
    build:
      context: .
      dockerfile: assets/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - symfony
    # volumes:
    #   - ./assets:/app
    # Add other necessary configurations for your Vue.js service

  symfony:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    # volumes:
    #   - .:/var/www/html
    # Add other necessary configurations for your Symfony service
    depends_on:
      - db
  db:
    image: mysql # Use the official MySQL 5.7 image as the base image
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8101:3306"