version: '3'

services:
  symfony:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    # Add other necessary configurations for your Symfony service
    depends_on:
      - db

  vue:
    build:
      context: .
      dockerfile: assets/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./assets:/app
    # Add other necessary configurations for your Vue.js service

  db:
    image: mysql # Use the official MySQL 5.7 image as the base image
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8101:3306"